import streamlit as st
import pandas as pd
import os
from fpdf import FPDF
import io

st.set_page_config(page_title="IHOP OE One Pager", layout="wide")

FILE_PATH = "OE_Opportunities_Classification.xlsx"
LOGO_PATH = "ihop_logo.png"

# Initialize or load data
if os.path.exists(FILE_PATH):
    df = pd.read_excel(FILE_PATH)
else:
    df = pd.DataFrame(columns=["Opportunity", "Classification"])

st.title("🥞 IHOP OE One Pager")

st.markdown("### Paste text here *(one line per row)*")
user_input = st.text_area(
    "",
    placeholder="Paste text here (one line per row)",
    height=150
)

# Handle pasted text
if user_input.strip():
    new_items = [line.strip() for line in user_input.split("\n") if line.strip()]
    new_df = pd.DataFrame(new_items, columns=["Opportunity"])
    df = pd.concat([df, new_df], ignore_index=True).drop_duplicates(subset=["Opportunity"])

# Interface for verification/classification
st.markdown("## Please Verify Each Opportunity (FOH / BOH / BOTH)")

updated_rows = []
for i, row in df.iterrows():
    if pd.isna(row["Classification"]) or row["Classification"] == "":
        st.markdown(f"⚠️ **{row['Opportunity']}**")
    else:
        st.markdown(f"**{row['Opportunity']}**")

    classification = st.radio(
        f"Select category for: {row['Opportunity']}",
        ["", "FOH", "BOH", "BOTH"],
        index=["", "FOH", "BOH", "BOTH"].index(row["Classification"]) if row["Classification"] in ["FOH", "BOH", "BOTH"] else 0,
        key=f"class_{i}",
        horizontal=True
    )
    updated_rows.append({"Opportunity": row["Opportunity"], "Classification": classification})

# Save updates
df = pd.DataFrame(updated_rows)
df.to_excel(FILE_PATH, index=False)
st.success(f"✅ Classifications saved to {FILE_PATH}")

# Status banner
unclassified = df["Classification"].isna().sum() + (df["Classification"] == "").sum()
if unclassified > 0:
    st.warning(f"⚠ {unclassified} opportunities still need classification.")
else:
    st.success("✅ All opportunities have been verified and classified!")

# PDF info inputs
st.markdown("---")
st.markdown("### 🏪 PDF Export Details")
store_number = st.text_input("Store Number", placeholder="e.g., 4445")
oe_cycle = st.text_input("OE Cycle", placeholder="e.g., Cycle 2 - July 2025")

# PDF generator
def generate_pdf(dataframe, store_number, oe_cycle):
    pdf = FPDF()
    pdf.add_page()

    # Logo
    if os.path.exists(LOGO_PATH):
        pdf.image(LOGO_PATH, x=80, y=8, w=50)
        pdf.ln(35)
    else:
        pdf.set_font("Arial", "B", 16)
        pdf.cell(200, 10, txt="IHOP OE One Pager", ln=True, align="C")
        pdf.ln(10)

    # Header
    pdf.set_font("Arial", "B", 14)
    pdf.cell(0, 10, f"Store #: {store_number}", ln=True, align="C")
    pdf.cell(0, 10, f"OE Cycle: {oe_cycle}", ln=True, align="C")
    pdf.ln(10)

    # Group by classification
    pdf.set_font("Arial", "B", 12)
    for section in ["FOH", "BOH", "BOTH"]:
        filtered = dataframe[dataframe["Classification"] == section]
        if not filtered.empty:
            pdf.cell(0, 10, txt=f"{section} Opportunities", ln=True)
            pdf.set_font("Arial", size=11)
            for _, row in filtered.iterrows():
                pdf.multi_cell(0, 8, f"• {row['Opportunity']}")
            pdf.ln(5)
            pdf.set_font("Arial", "B", 12)

    # Footer
    pdf.set_font("Arial", "I", 9)
    pdf.cell(0, 10, txt="Generated by IHOP OE One Pager", ln=True, align="C")

    buffer = io.BytesIO()
    pdf.output(buffer)
    return buffer.getvalue()

# Generate PDF only when ready
if st.button("📄 Generate One-Pager PDF"):
    if not store_number or not oe_cycle:
        st.error("⚠ Please enter both Store Number and OE Cycle before generating the PDF.")
    else:
        pdf_bytes = generate_pdf(df, store_number, oe_cycle)
        st.download_button(
            label="⬇ Download One-Pager PDF",
            data=pdf_bytes,
            file_name=f"OE_OnePager_{store_number}_{oe_cycle}.pdf",
            mime="application/pdf"
        )
